version: '2'
services:
  db:
    restart: unless-stopped
    image: postgres:9.6
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=backoffice
      - POSTGRES_PASSWORD=passsword
      - POSTGRES_DB=backoffice
    volumes:
      - ./data/db:/var/lib/postgresql/data
  redis:
    restart: unless-stopped
    image: redis:alpine
    volumes:
      - ./data/redis:/data
  worker:
    restart: unless-stopped
    build: .
    environment:
      - DATABASE_URL=postgres://backoffice:passsword@db/backoffice
      - REDISTOGO_URL=redis://redis:6379/
      - FLASK_CONFIG=production
    env_file: secrets.env
    command: python -u manage.py run_worker
    volumes:
      - ./data/public:/code/public
    links:
      - db
      - redis
  web:
    restart: unless-stopped
    build: .
    environment:
      - DATABASE_URL=postgres://backoffice:passsword@db/backoffice
      - REDISTOGO_URL=redis://redis:6379/
      - VIRTUAL_HOST=backoffice.bewegung.jetzt
      - LETSENCRYPT_HOST=backoffice.bewegung.jetzt
      - LETSENCRYPT_EMAIL=domains@bewegung.jetzt
      - FLASK_CONFIG=production
    env_file: secrets.env
    command: gunicorn manage:app -b 0.0.0.0
    volumes:
      - ./data/public:/code/public
    expose:
      - 8000
    links:
      - db
      - redis

networks:
  default:
   external:
     name: nginx-proxy
